DROP DATABASE IF EXISTS sqlsi2020;
CREATE DATABASE sqlsi2020 
 DEFAULT CHARACTER SET utf8 
 DEFAULT COLLATE utf8_general_ci;
USE sqlsi2020;
CREATE TABLE Lecturer (Lecturer_id VARCHAR (100) NOT NULL PRIMARY KEY, email VARCHAR (100) );
CREATE TABLE Student (Student_id VARCHAR (100) NOT NULL PRIMARY KEY, email VARCHAR (100) );
CREATE TABLE Enrollment (lecturers VARCHAR (100), students VARCHAR (100));
ALTER TABLE Enrollment ADD FOREIGN KEY (lecturers) REFERENCES Lecturer (Lecturer_id), ADD FOREIGN KEY (students) REFERENCES Student (Student_id);
